# 01 - Download: all NYC Citi Bike data (2013 - now)

**Who worked on this:** Mohammed AbuQamar

**What this notebook does:** download every NYC trip archive, unpack it and assemble everything into parquet files with one common set of column names. All the logic lives in `src/download.py`, so the retraining pipeline can run the same code.

**What is in the bucket** (checked on the [Citi Bike S3 bucket](https://s3.amazonaws.com/tripdata/index.html)):
- 2013 - 2023: one zip per **year**; 2024 onwards: one zip per **month**
- about **32 GB of zips** for NYC, roughly 352 million trips
- `JC-...` files are Jersey City, a separate system: skipped

**Two different schemas.** Up to January 2021 the columns are `tripduration, starttime, usertype, birth year, ...` (and in late 2016 they were even written as `Trip Duration, Start Time, ...`). From February 2021 they are `ride_id, rideable_type, started_at, member_casual, ...`. To assemble one dataset we map every header to one canonical name (`src/cleaning.canonical_name`). **Only the names change here; every value stays raw text.** Cleaning the values is done in 02/03.


- **Resumable:** finished archives are written to `raw/_done.txt`. If it crashes or you stop it, just run it again.
- Parquet instead of CSV: we used csv but it was much slower so after we looked into itn we landed on parquet it is smaller, and lighter give less strees on th ram beacuse Duck Db just straem the data

In [2]:
import sys
sys.path.append(".")
import pandas as pd
import duckdb
from src.download import list_archives, download_all, RAW_DIR

## 1. Which archives are there?
Read from the bucket listing itself, so new months are picked up automatically when this runs again later.

In [3]:
archives = list_archives()
print(len(archives), "NYC archives:", archives[0], "...", archives[-1])
pd.Series([a[:4] for a in archives]).value_counts().sort_index().to_frame("archives per year").T

44 NYC archives: 2013-citibike-tripdata.zip ... 202609-citibike-tripdata.zip

,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
archives per year,1,1,1,1,1,1,1,1,1,1,1,12,12,9

## 2. Download and convert
`YEARS = None` downloads everything. To test quickly first, use e.g. `YEARS = [2016, 2024]`: one legacy and one current year. Running it again later with `None` only downloads what is still missing.

In [4]:
YEARS = None
archives = download_all(years=YEARS)
print("Done:", len(archives), "archives")

44 archives, 0 already done, 44 to go
Downloading 2013-citibike-tripdata.zip ...
  converting 201309-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201311-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201307-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201308-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201306-citibike-tripdata.csv
  converting 201310-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201312-citibike-tripdata.csv
  converting 201312-citibike-tripdata_1.csv
  converting 201311-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201307-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201310-citibike-tripdata_2.csv
  converting 201310-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201309-citibike-tripdata_2.csv
  converting 201309-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201308-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201308-citibike-tripdata_2.csv
  converting 201306-citibike-tripdata_1.csv
Downloading 2014-citibike-tripdata.zip ...
  converting 201404-citibike-tripdata_1.csv
  converting 201412-citibike-tripdata_1.csv
  converting 201411-citibike-tripdata_1.csv
  converting 201407-citibike-tripdata_1.csv
  converting 201410-citibike-tripdata_1.csv
  converting 201409-citibike-tripdata_1.csv
  converting 201408-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201406-citibike-tripdata_1.csv
  converting 201403-citibike-tripdata_1.csv
  converting 201401-citibike-tripdata_1.csv
  converting 201402-citibike-tripdata_1.csv
  converting 201405-citibike-tripdata_1.csv
Downloading 2015-citibike-tripdata.zip ...
  converting 201504-citibike-tripdata_1.csv
  converting 201512-citibike-tripdata_1.csv
  converting 201511-citibike-tripdata_1.csv
  converting 201507-citibike-tripdata_1.csv
  converting 201507-citibike-tripdata_2.csv
  converting 201510-citibike-tripdata_2.csv
  converting 201510-citibike-tripdata_1.csv
  converting 201509-citibike-tripdata_2.csv
  converting 201509-citibike-tripdata_1.csv
  converting 201508-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201508-citibike-tripdata_2.csv
  converting 201506-citibike-tripdata_1.csv
  converting 201503-citibike-tripdata_1.csv
  converting 201501-citibike-tripdata_1.csv
  converting 201502-citibike-tripdata_1.csv
  converting 201505-citibike-tripdata_1.csv
Downloading 2016-citibike-tripdata.zip ...
  converting 201604-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201604-citibike-tripdata_2.csv
  converting 201612-citibike-tripdata_1.csv
  converting 201611-citibike-tripdata_2.csv
  converting 201611-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201607-citibike-tripdata_2.csv
  converting 201607-citibike-tripdata_1.csv
  converting 201610-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201610-citibike-tripdata_2.csv
  converting 201609-citibike-tripdata_1.csv
  converting 201609-citibike-tripdata_2.csv
  converting 201608-citibike-tripdata_2.csv
  converting 201608-citibike-tripdata_1.csv
  converting 201606-citibike-tripdata_1.csv
  converting 201606-citibike-tripdata_2.csv
  converting 201603-citibike-tripdata_1.csv
  converting 201601-citibike-tripdata_1.csv
  converting 201602-citibike-tripdata_1.csv
  converting 201605-citibike-tripdata_2.csv
  converting 201605-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 2017-citibike-tripdata.zip ...
  converting 201704-citibike-tripdata.csv_1.csv
  converting 201704-citibike-tripdata.csv_2.csv
  converting 201712-citibike-tripdata.csv_1.csv
  converting 201711-citibike-tripdata.csv_2.csv
  converting 201711-citibike-tripdata.csv_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201707-citibike-tripdata.csv_2.csv
  converting 201707-citibike-tripdata.csv_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201710-citibike-tripdata.csv_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201710-citibike-tripdata.csv_2.csv
  converting 201709-citibike-tripdata.csv_2.csv
  converting 201709-citibike-tripdata.csv_1.csv
  converting 201708-citibike-tripdata.csv_1.csv
  converting 201708-citibike-tripdata.csv_2.csv
  converting 201706-citibike-tripdata.csv_1.csv
  converting 201706-citibike-tripdata.csv_2.csv
  converting 201703-citibike-tripdata.csv_1.csv
  converting 201701-citibike-tripdata.csv_1.csv
  converting 201702-citibike-tripdata.csv_1.csv
  converting 201705-citibike-tripdata.csv_2.csv
  converting 201705-citibike-tripdata.csv_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 2018-citibike-tripdata.zip ...
  converting 201809-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201801-citibike-tripdata.csv
  converting 201803-citibike-tripdata.csv
  converting 201805-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201807-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201811-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201804-citibike-tripdata_1.csv
  converting 201804-citibike-tripdata_2.csv
  converting 201808-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201802-citibike-tripdata.csv
  converting 201812-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201804-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201810-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201806-citibike-tripdata.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201804-citibike-tripdata_1.csv
  converting 201804-citibike-tripdata_2.csv
  converting 201812-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201812-citibike-tripdata_2.csv
  converting 201811-citibike-tripdata_2.csv
  converting 201811-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201807-citibike-tripdata_2.csv
  converting 201807-citibike-tripdata_1.csv
  converting 201810-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201810-citibike-tripdata_2.csv
  converting 201809-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201809-citibike-tripdata_2.csv
  converting 201808-citibike-tripdata_2.csv
  converting 201808-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201806-citibike-tripdata_1.csv
  converting 201806-citibike-tripdata_2.csv
  converting 201803-citibike-tripdata_1.csv
  converting 201801-citibike-tripdata_1.csv
  converting 201802-citibike-tripdata_1.csv
  converting 201805-citibike-tripdata_2.csv
  converting 201805-citibike-tripdata_1.csv
Downloading 2019-citibike-tripdata.zip ...
  converting 201904-citibike-tripdata_2.csv
  converting 201904-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201912-citibike-tripdata_1.csv
  converting 201911-citibike-tripdata_1.csv
  converting 201911-citibike-tripdata_2.csv
  converting 201907-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201907-citibike-tripdata_3.csv
  converting 201907-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201910-citibike-tripdata_3.csv
  converting 201910-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201910-citibike-tripdata_1.csv
  converting 201909-citibike-tripdata_3.csv
  converting 201909-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201909-citibike-tripdata_1.csv
  converting 201908-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201908-citibike-tripdata_2.csv
  converting 201908-citibike-tripdata_3.csv
  converting 201906-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201906-citibike-tripdata_3.csv
  converting 201906-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201903-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201903-citibike-tripdata_2.csv
  converting 201901-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 201902-citibike-tripdata_1.csv
  converting 201905-citibike-tripdata_1.csv
  converting 201905-citibike-tripdata_2.csv
Downloading 2020-citibike-tripdata.zip ...
  converting 202004-citibike-tripdata_1.csv
  converting 202012-citibike-tripdata_1.csv
  converting 202012-citibike-tripdata_2.csv
  converting 202006-citibike-tripdata_1.csv
  converting 202006-citibike-tripdata_2.csv
  converting 202010-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202010-citibike-tripdata_2.csv
  converting 202010-citibike-tripdata_3.csv
  converting 202008-citibike-tripdata_3.csv
  converting 202008-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202008-citibike-tripdata_1.csv
  converting 202002-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202002-citibike-tripdata_2.csv
  converting 202005-citibike-tripdata_2.csv
  converting 202005-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202011-citibike-tripdata_2.csv
  converting 202011-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202007-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202007-citibike-tripdata_3.csv
  converting 202007-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202009-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202009-citibike-tripdata_2.csv
  converting 202009-citibike-tripdata_3.csv
  converting 202001-citibike-tripdata_2.csv
  converting 202001-citibike-tripdata_1.csv
  converting 202003-citibike-tripdata_2.csv
  converting 202003-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 2021-citibike-tripdata.zip ...
  converting 202107-citibike-tripdata_4.csv
  converting 202107-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202107-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202107-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202111-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202111-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202111-citibike-tripdata_3.csv
  converting 202105-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202105-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202105-citibike-tripdata_3.csv
  converting 202103-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202103-citibike-tripdata_2.csv
  converting 202101-citibike-tripdata_1.csv
  converting 202101-citibike-tripdata_2.csv
  converting 202109-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202109-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202109-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202109-citibike-tripdata_4.csv
  converting 202110-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202110-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202110-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202110-citibike-tripdata_4.csv
  converting 202106-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202106-citibike-tripdata_3.csv
  converting 202106-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202106-citibike-tripdata_4.csv
  converting 202112-citibike-tripdata_2.csv
  converting 202112-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202104-citibike-tripdata_3.csv
  converting 202104-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202104-citibike-tripdata_1.csv
  converting 202102-citibike-tripdata_1.csv
  converting 202108-citibike-tripdata_4.csv
  converting 202108-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202108-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202108-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 2022-citibike-tripdata.zip ...
  converting 202209-citibike-tripdata_4.csv
  converting 202209-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202209-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202209-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202201-citibike-tripdata_2.csv
  converting 202201-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202203-citibike-tripdata_2.csv
  converting 202203-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202205-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202205-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202205-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202207-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202207-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202207-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202207-citibike-tripdata_4.csv
  converting 202211-citibike-tripdata_3.csv
  converting 202211-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202211-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202208-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202208-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202208-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202208-citibike-tripdata_4.csv
  converting 202202-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202202-citibike-tripdata_2.csv
  converting 202212-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202212-citibike-tripdata_2.csv
  converting 202204-citibike-tripdata_1.csv
  converting 202204-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202204-citibike-tripdata_3.csv
  converting 202210-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202210-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202210-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202206-citibike-tripdata_4.csv
  converting 202206-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202206-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202206-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 2023-citibike-tripdata.zip ...
  converting 202302-citibike-tripdata_2.csv
  converting 202302-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202308-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202308-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202308-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202308-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202306-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202306-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202306-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202306-citibike-tripdata_4.csv
  converting 202310-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202310-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202310-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202310-citibike-tripdata_4.csv
  converting 202304-citibike-tripdata_3.csv
  converting 202304-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202304-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202312-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202312-citibike-tripdata_3.csv
  converting 202312-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202303-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202303-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202303-citibike-tripdata_3.csv
  converting 202301-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202301-citibike-tripdata_2.csv
  converting 202309-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202309-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202309-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202309-citibike-tripdata_4.csv
  converting 202311-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202311-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202311-citibike-tripdata_3.csv
  converting 202307-citibike-tripdata_4.csv
  converting 202307-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202307-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202307-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202305-citibike-tripdata_4.csv
  converting 202305-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202305-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202305-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202401-citibike-tripdata.zip ...
  converting 202401-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202401-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202402-citibike-tripdata.zip ...
  converting 202402-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202402-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202402-citibike-tripdata_3.csv
Downloading 202403-citibike-tripdata.zip ...
  converting 202403-citibike-tripdata_3.csv
  converting 202403-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202403-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202404-citibike-tripdata.zip ...
  converting 202404-citibike-tripdata_4.csv
  converting 202404-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202404-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202404-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202405-citibike-tripdata.zip ...
  converting 202405-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202405-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202405-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202405-citibike-tripdata_5.csv
  converting 202405-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202406-citibike-tripdata.zip ...
  converting 202406-citibike-tripdata_5.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202406-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202406-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202406-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202406-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202407-citibike-tripdata.zip ...
  converting 202407-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202407-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202407-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202407-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202407-citibike-tripdata_5.csv
Downloading 202408-citibike-tripdata.zip ...
  converting 202408-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202408-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202408-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202408-citibike-tripdata_5.csv
  converting 202408-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202409-citibike-tripdata.zip ...
  converting 202409-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202409-citibike-tripdata_5.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202409-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202409-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202409-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202410-citibike-tripdata.zip ...
  converting 202410-citibike-tripdata_6.csv
  converting 202410-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202410-citibike-tripdata_5.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202410-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202410-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202410-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202411-citibike-tripdata.zip ...
  converting 202411-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202411-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202411-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202411-citibike-tripdata_4.csv
Downloading 202412-citibike-tripdata.zip ...
  converting 202412-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202412-citibike-tripdata_3.csv
  converting 202412-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202501-citibike-tripdata.zip ...
  converting 202501-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202501-citibike-tripdata_3.csv
  converting 202501-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202502-citibike-tripdata.zip ...
  converting 202502-citibike-tripdata_3.csv
  converting 202502-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202502-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202503-citibike-tripdata.zip ...
  converting 202503-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202503-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202503-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202503-citibike-tripdata_4.csv
Downloading 202504-citibike-tripdata.zip ...
  converting 202504-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202504-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202504-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202504-citibike-tripdata_4.csv
Downloading 202505-citibike-tripdata.zip ...
  converting 202505-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202505-citibike-tripdata_5.csv
  converting 202505-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202505-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202505-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202506-citibike-tripdata.zip ...
  converting 202506-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202506-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202506-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202506-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202506-citibike-tripdata_5.csv
Downloading 202507-citibike-tripdata.zip ...
  converting 202507-citibike-tripdata_5.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202507-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202507-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202507-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202507-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202508-citibike-tripdata.zip ...
  converting 202508-citibike-tripdata_6.csv
  converting 202508-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202508-citibike-tripdata_5.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202508-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202508-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202508-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202509-citibike-tripdata.zip ...
  converting 202509-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202509-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202509-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202509-citibike-tripdata_5.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202509-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202509-citibike-tripdata_6.csv
Downloading 202510-citibike-tripdata.zip ...
  converting 202510-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202510-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202510-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202510-citibike-tripdata_5.csv
  converting 202510-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202511-citibike-tripdata.zip ...
  converting 202511-citibike-tripdata_4.csv
  converting 202511-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202511-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202511-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202512-citibike-tripdata.zip ...
  converting 202512-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202512-citibike-tripdata_3.csv
  converting 202512-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202601-citibike-tripdata.zip ...
  converting 202601-citibike-tripdata_2.csv
  converting 202601-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202602-citibike-tripdata.zip ...
  converting 202602-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202602-citibike-tripdata_2.csv
Downloading 202603-citibike-tripdata.zip ...
  converting 202603-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202603-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202603-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202604-citibike-tripdata.zip ...
  converting 202604-citibike-tripdata-part1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202604-citibike-tripdata-part2.csv
  converting 202604-citibike-tripdata-part3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202604-citibike-tripdata-part4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202605-citibike-tripdata.zip ...
  converting 202605-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202605-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202605-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202605-citibike-tripdata_5.csv
  converting 202605-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202606-citibike-tripdata.zip ...
  converting 202606-citibike-tripdata_6.csv
  converting 202606-citibike-tripdata_5.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202606-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202606-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202606-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202606-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202607-citibike-tripdata.zip ...
  converting 202607-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202607-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202607-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202607-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202607-citibike-tripdata_5.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Downloading 202608-citibike-tripdata.zip ...
  converting 202608-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202608-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202608-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202608-citibike-tripdata_5.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202608-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202608-citibike-tripdata_6.csv
Downloading 202609-citibike-tripdata.zip ...
  converting 202609-citibike-tripdata_4.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202609-citibike-tripdata_5.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202609-citibike-tripdata_1.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202609-citibike-tripdata_2.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  converting 202609-citibike-tripdata_3.csv

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Done: 44 archives

## 3. Check the result
Trips per year, and which canonical columns are filled in which period. The schema change of 2021 should be clearly visible.

In [5]:
con = duckdb.connect()
src = f"read_parquet('{RAW_DIR.as_posix()}/**/*.parquet', filename=true, union_by_name=true)"
per_year = con.execute(f'''
    SELECT left(regexp_extract(replace(filename, '\\', '/'), 'raw/([0-9]+)/', 1), 4) AS year,
           count(*) AS trips,
           round(100 * avg((ride_id IS NOT NULL)::INT), 1)     AS pct_with_ride_id,
           round(100 * avg((birth_year IS NOT NULL)::INT), 1)  AS pct_with_birth_year
    FROM {src} GROUP BY 1 ORDER BY 1''').df()
display(per_year)
print(f"Total: {per_year.trips.sum():,} trips")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

    year     trips  pct_with_ride_id  pct_with_birth_year
0   2013  11229776               0.0                 97.9
1   2014   8081216               0.0                 97.4
2   2015   9937969               0.0                 86.8
3   2016  13845655               0.0                 88.5
4   2017  16364657               0.0                 90.0
5   2018  35096678               0.0                100.0
6   2019  20551697               0.0                100.0
7   2020  19562314             100.0                  0.0
8   2021  27130122             100.0                  0.0
9   2022  29838806             100.0                  0.0
10  2023  35106986             100.0                  0.0
11  2024  44303209             100.0                  0.0
12  2025  45771102             100.0                  0.0
13  2026  35143533             100.0                  0.0

Total: 351,963,720 trips

`pct_with_ride_id` should be ~0 before 2021 and ~100 after, `pct_with_birth_year` the other way around. 2021 contains both (January is still legacy).